apiVersion: apps/v1
kind: Deployment
metadata:
  name: python1
  #namespace: siva-k8s
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: c27
        image: lokeshudatha/java:v01
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: python-service1
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - targetPort: 5000
      port: 80
