apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
  namespace: siva-k8s
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: c26
        image: lokeshudatha/sonar:v1
        ports:
        - containerPort: 8080
